### ISSUE TITLE
Sitios de interés en el mapa

### ISSUE THREAD

**Issue by MaCuur** [grupoioa/gis_agm_series#33]
Puntos relevantes

https://www.google.com/maps/d/edit?mid=1orvZS-g2SOjLkT6j7KJbfCQ-PwoYum4x&usp=sharing

igual KMZ te funciona mejor
si no, deja instalo arcgis y te lo mando

**Comment by MaCuur** [comment]
> Puntos relevantes
> 
> https://www.google.com/maps/d/edit?mid=1orvZS-g2SOjLkT6j7KJbfCQ-PwoYum4x&usp=sharing
> 
> igual KMZ te funciona mejor si no, deja instalo arcgis y te lo mando

**Comment by MaCuur** [comment]
también se podrían añadir los puntos de los pozos petroleros que ya se usan en owgis en lo que tienen la junta

**Comment by ma-robles** [comment]
es buena propuesta lo de los pozos petroleros, las coordenadas las debe tener @AndreaAnguiano. En cuanto al KMZ, creo que geoserver no admite ese formato,  así es que sí necesitamos el shape :(. creí que ya lo tenías instalado, dado que estabas haciendo mapas y rayones

**Comment by MaCuur** [comment]
Por cierto, me acaba de surgir la duda... ¿en dónde te comparto los archivos?

**Comment by ma-robles** [comment]
pues ya estuve checando y leaflet no acepta por sí solo los shape... entonces tendrá que ser geojson. Me parece mejor opción porque también es lo que maneja echarts si se hace alguna migración futura y no requieres arcgis ni nada muy sofisticado para crearlos. Los puedes generar [aquí](http://geojson.io) (o con lo que te acomodes).
En teoría no deben salir archivos muy grandes, por lo que lo puedes agregar el archivo en un commit a la rama plot... o incluso directo a main

**Comment by MaCuur** [comment]
Genial!! mucho mejor.
