### ISSUE TITLE
DUDA.El mapa (creo que es de google), ¿no tiene restricciones de uso?

### ISSUE THREAD

**Issue by AbrilIchel** [grupoioa/gis_agm_series#71]

**Comment by ma-robles** [comment]
Si, pero no estoy seguro de si las estamos infringiendo (adjunto enlace abajo). Igual se puede poner otra capa que tenga permisos más abiertos o una propia, de hecho creo que Cuau ya había hecho una.

[https://maps.google.com/help/terms_maps/](https://maps.google.com/help/terms_maps/)

**Comment by ma-robles** [comment]
ya quitamos ese mapa así que ya no tenemos ese problema
