### ISSUE TITLE
Corrección en la plataforma a considerar

### ISSUE THREAD

**Issue by AbrilIchel** [grupoioa/gis_agm_series#99]
Aún falta corregir el periodo, el correcto lo estamos manejando como 1979-2017
![image](https://user-images.githubusercontent.com/98612287/203649599-13c5eb69-90a3-4b98-8deb-d0fb1ae0393d.png)

**Comment by MaCuur** [comment]
@ma-robles

**Comment by ma-robles** [comment]
upsi

**Comment by ma-robles** [comment]
@MaCuur  Hecho!

![image](https://github.com/grupoioa/gis_agm_series/assets/20845249/77df2950-a5b9-4b74-b800-d78f815cbaf7)
